language: cpp
branches:
    only:
        - /^v\d+\..+$/
        - master
        - ci
        - travis
        - hunter
        - /^release.*$/
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          env: CUDA=ON
cache:
    directories:
        - $HOME/.local
before_install: |
    if [ "$CUDA" = ON ]; then
      . scripts/install-cuda-ubuntu1604.sh
    fi
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      scripts/install_cmake.sh
      pyenv local 3.6
      pip install --user requests
    elif [ "$TRAVIS_OS_NAME" == "osx" ]; then
      HOMEBREW_NO_AUTO_UPDATE=1 brew install -q python3
      pip3 install -q requests
    fi
script:
    - cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=$CUDA -DETHASHCL=ON -DAPICORE=ON -H. -Bbuild
    - cmake --build build -- -j4
    - build/ethminer/ethminer --list-devices -G
    - build/ethminer/ethminer --list-devices -U
    - if [ "$TRAVIS_OS_NAME" = linux ]; then ldd -v build/ethminer/ethminer; fi
    - if [ "$TRAVIS_OS_NAME" = osx ]; then otool -L build/ethminer/ethminer; fi
    - cmake --build build --target package


deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/ethminer/ethminer
    skip_cleanup: true
    on:
     tags: true
